import React, { FC, ReactNode } from "react";
import styled from "styled-components";
import { Paragraph } from "@looker/components";
import { round } from "lodash/fp";
import SectionHeading from "./SectionHeading";
import { Whale } from "./assets";
import { numberFormat, massInLbs } from "./utilities";

interface WhaleProps {
  totalCarbon: number;
}

function pluralize(string: string, amount: number) {
  return amount === 1 ? string : `${string}s`;
}

const WhaleChart: FC<WhaleProps> = ({ totalCarbon }) => {
  const whaleWeight = 75000; // kilograms
  const totalWhales = round(totalCarbon / whaleWeight);
  const Chart = Array(totalWhales).fill(Whale);

  return (
    <div>
      <SectionHeading as="h2">Did you know?</SectionHeading>
      <Paragraph fontWeight="light" mt="large" mb="large">
        A full grown blue whale has a mass of {numberFormat(whaleWeight)} kg, or{" "}
        {numberFormat(massInLbs(whaleWeight))} pounds.
      </Paragraph>
      <Paragraph fontWeight="light" mt="large" mb="large">
        The carbon generated by JOIN attendee travel is equivalent to the weight
        of{" "}
        <Strong>
          {Chart.length} blue {pluralize("whale", Chart.length)}.
        </Strong>
      </Paragraph>
      {Chart.map((Glyph, i) => (
        <Spacer key={i}>
          <Glyph />
        </Spacer>
      ))}
    </div>
  );
};

export default WhaleChart;

interface ElementProps {
  children: ReactNode;
}

const Spacer = styled.span<ElementProps>`
  display: inline-block;
  margin: 0 ${({ theme }) => theme.space.xxsmall}
    ${({ theme }) => theme.space.xxsmall} 0;
`;

const Strong = styled.strong<ElementProps>`
  font-weight: 600;
  color: ${({ theme }) => theme.colors.palette.purple400};
`;
